stages:
  - build
  - test

rust-latest-build:
  stage: build
  image: rust:latest
  script:
    - sed -i 's/\.\.\/bgpsim-macros/bgpsim-macros/g' Cargo.toml
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ethz.ch/nsg/employees/sctibor/projects/bgpsim-macros bgpsim-macros
    - cargo build --verbose
    - cargo build --verbose --all-features

rust-nightly-build:
  stage: build
  image: rustlang/rust:nightly
  script:
    - sed -i 's/\.\.\/bgpsim-macros/bgpsim-macros/g' Cargo.toml
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ethz.ch/nsg/employees/sctibor/projects/bgpsim-macros bgpsim-macros
    - cargo build --verbose
    - cargo build --verbose --all-features
  allow_failure: true

rust-latest-test:
  stage: test
  image: rust:latest
  script:
    - sed -i 's/\.\.\/bgpsim-macros/bgpsim-macros/g' Cargo.toml
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ethz.ch/nsg/employees/sctibor/projects/bgpsim-macros bgpsim-macros
    - cargo test --verbose --tests --release
    - cargo test --verbose --tests --all-features --release
    - cargo test --verbose --doc --all-features

rust-nightly-test:
  stage: test
  image: rustlang/rust:nightly
  script:
    - sed -i 's/\.\.\/bgpsim-macros/bgpsim-macros/g' Cargo.toml
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ethz.ch/nsg/employees/sctibor/projects/bgpsim-macros bgpsim-macros
    - cargo test --verbose --tests --release
    - cargo test --verbose --tests --all-features --release
    - cargo test --verbose --doc --all-features
  allow_failure: true
