stages:
  - build

rust-latest-build:
  stage: build
  image: rust:latest
  script:
    - cargo install --locked trunk
    - cargo install --locked wasm-bindgen-cli
    - curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
    - chmod +x tailwindcss-linux-x64
    - mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss
    - trunk build
    - trunk build --features "atomic_bgp"

rust-nightly-build:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo install --locked trunk
    - cargo install --locked wasm-bindgen-cli
    - curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
    - chmod +x tailwindcss-linux-x64
    - mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss
    - trunk build
    - trunk build --features "atomic_bgp"
  allow_failure: true
