[package]
name = "netsim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
undo = []

[dependencies]
thiserror = "1"
petgraph = "0.6"
log = "0.4"
itertools = "0.10"
priority-queue = "1.2.2"
rand = "0.8.4"
rand_distr = "0.4.3"
ordered-float = "3.0.0"
lazy_static = "1.4.0"

[dev-dependencies]
rand = "0.8.4"
maplit = "1.0.2"
env_logger = "0.9.0"
